In [1]:
import numpy as np

#### (1) FOR LOOP PRACTICE
- (a.) Create a *list* consisting of the names of my three favorite cities:  Boulder, State College, and Urbana :) 
<br><br>
- (b.) Write a for loop that prints out the name of each of these cities!
<br><br>

*Recall that this could be done as:*
<br>
&emsp;for i in range(3):<br>
&emsp;&emsp;print(list[i])
<br>

where *range(3)* is the iterable object -> but in your lesson, we also talked about another, more Pythonic way to do this where the data itself is the *iterable object*

In [3]:
# Create a *list* consisting of the names of my three favorite cities:  Boulder, State College, and Urbana
cities = ['Boulder', 'State College', 'Urbana']
print(cities)

['Boulder', 'State College', 'Urbana']


In [4]:
# Write a for loop that prints out the name of each of these cities
for city in cities:
    print(city)

Boulder
State College
Urbana


#### (2) WHILE LOOP PRACTICE
- (a.) construct a while loop to sum up the values of 1 through 9, and then print out the sum after the loop is done, as well as the value of i

In [5]:
# construct a while loop to sum up the values of 1 through 9, and then print out the sum after the loop is done, as well as the value of i
i = 1
sum = 0
while i <= 9:
    sum += i
    i += 1
# print out the sum after the loop is done, as well as the value of i
print(sum)
print(i)

# Answer: 45!

45
10


#### (3) ARRAY OPERATIONS
- (a.) Convert the temperatures in array d, which are in degrees Fahrenheit, to degrees Celsius, using array operations, and save to a new variable (i.e., *don't overwrite d*)
<br><br>
- (b.) Convert array d to an 1D array and save to a new variable (i.e., *don't overwrite d*)

In [6]:
# Temperatures on a grid on a summer's day 
d = np.array([[100,94,97,92,90,95],[93,87,98,96,93,89]])
print(d)

[[100  94  97  92  90  95]
 [ 93  87  98  96  93  89]]


In [7]:
# Convert the temperatures in array d, which are in degrees Fahrenheit, to degrees Celsius, using array operations, and save to a new variable (i.e., *don't overwrite d*)
d_celsius = (d - 32) * 5/9
print(d_celsius)

[[37.77777778 34.44444444 36.11111111 33.33333333 32.22222222 35.        ]
 [33.88888889 30.55555556 36.66666667 35.55555556 33.88888889 31.66666667]]


In [8]:
# Convert array d to an 1D array and save to a new variable (i.e., *don't overwrite d*)
d_1d = d.flatten()
print(d_1d)


[100  94  97  92  90  95  93  87  98  96  93  89]


#### (4) ARRAY COMPARISON + LOGICAL OPERATIONS 
***REMINDER: USE ARRAY IN DEGREES FAHRENHEIT FOR ALL QUESTIONS IN 4***
- (a.) identify and print only elements in array d that are above 95

In [9]:
# identify and print only elements in array d that are above 95
print(d[d > 95])

[100  97  98  96]


- (b.) identify and print elements in array d that are above 95 AND are divisble by 2

In [10]:
# identify and print elements in array d that are above 95 AND are divisble by 2
print(d[(d > 95) & (d % 2 == 0)])

[100  98  96]


- (c.) calculate how many elements in d are above 95

In [11]:
# calculate how many elements in d are above 95
print(np.sum(d > 95))
# Answer: 4 (using array in deg F)

4


- (d.) calculate the mean of all elements in d that are above 95

In [12]:
# calculate the mean of all elements in d that are above 95
print(np.mean(d[d > 95]))
# Answer: 97.75 (using array in deg F)

97.75


## Quiz: 

In [2]:
g = np.array([[2, 4, 6, 8, 10], [12, 14, 16, 18, 20]] )

In [3]:
# print the shape of g
print(g.shape)

(2, 5)


In [4]:
np.mean(g, axis=0)

array([ 7.,  9., 11., 13., 15.])

In [5]:
np.mean(g, axis=1)

array([ 6., 16.])

In [6]:
np.mean(g)

11.0

In [7]:
g[g>12]

array([14, 16, 18, 20])

### 2.

In [8]:
for a in np.arange(0, 5):
    print(a)

0
1
2
3
4


# Broadcasting in Python

Broadcasting is a way to make arrays of the same shape, but with different values. There are three rules for broadcasting. Rule 1 is 

In [10]:
i = 0

while (i < 10):

    print(i)

    i = i+1




0
1
2
3
4
5
6
7
8
9


In [12]:
print("We are done!")

We are done!


In [13]:
wind_spd = 100
if wind_spd >=65 and wind_spd <=85:
    
    print ('Tornado rating: EF0')

elif wind_spd >=86 and wind_spd <=110:

    print ('Tornado rating: EF1')

elif wind_spd >=111 and wind_spd <=135:

    print ('Tornado rating: EF2')

elif wind_spd >=136 and wind_spd <=165:

    print ('Tornado rating: EF3')

elif wind_spd >=166 and wind_spd <=200:

    print ('Tornado rating: EF4')

elif wind_speed > 200:

    print('Tornado rating: EF5')

else:

    print('No tornado')

Tornado rating: EF1
