- import numpy package as alias 'np'

In [1]:
import numpy as np

# Array creation:
*please use NumPy functions rather than doing so manually*
- Create a 1D array, a, that consists of elements 1 through 10 (inclusive)
- Create a 1D array, b, that consists of elements 11 through 20 (inclusive)

In [12]:
# Create a 1D array, a, that consists of elements 1 through 10 (inclusive)
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
# Create a 1D array, b, that consists of elements 11 through 20 (inclusive)
b = np.arange(11, 21)
print(b)

[11 12 13 14 15 16 17 18 19 20]


- Add arrays a and b together and save the result in array c
  - Can use built-in Python operations, although you'll learn more options next week about mathematical operations in NumPy!

In [4]:
# Add arrays a and b together and save the result in array c
c = a + b
print(c)

[12 14 16 18 20 22 24 26 28 30]


# Array indexing

In [5]:
# Temperatures on a grid on a summer's day 
d = np.array([[100,94,96,92,90],[95,87,98,96,93]])
print(d)

[[100  94  96  92  90]
 [ 95  87  98  96  93]]


- Access and print the element in the first row, third column of d


In [6]:
# Access and print the element in the first row, third column of d
print(d[0,2])

96


- Access and print the elements in the second row, and the first through fourth (inclusive) columns of d

In [7]:
# Access and print the elements in the second row, and the first through fourth (inclusive) columns of d
print(d[1,:4])

[95 87 98 96]


# Array Characteristics
- calculate and print the maximum and minimum values in d

In [8]:
# calculate and print the maximum and minimum values in d
print(f"Maximum value in d: {np.max(d)}")
print(f"Minimum value in d: {np.min(d)}")

Maximum value in d: 100
Minimum value in d: 87


- calculate and print the shape of d
- in a comment, describe how many rows and columns d has

In [10]:
# calculate and print the shape of d
# in a comment, describe how many rows and columns d has
print(f"Shape of d: {d.shape}")  # d has 2 rows and 5 columns

Shape of d: (2, 5)


- calculate the size of d

In [11]:
# calculate the size of d
print(f"Size of d: {d.size}")

Size of d: 10
