In [1]:
import numpy as np
from matplotlib import pyplot as plt

In [2]:
# Read in the data from the text file
# Into a NumPy array called 'temperature'
temperature = np.genfromtxt('nhb_temperature_obs.txt')

In [3]:
# Create a 1D NumPy array consisting of the values 1, 2, 3, 4 
a = np.arange(1, 5)


In [6]:
# Print out each the heights and the temperature variables
print(f"The heights are {a}")
print(f"The temperature variables are 11am and 3 pm")
eleven_am = temperature[:, 0]
three_pm = temperature[:, 1]


The heights are [1 2 3 4]
The temperature variables are 11am and 3 pm


In [7]:
# What is the shape/dimensions of the temperature variable?
print(f"The shape of eleven_am is {eleven_am.shape}")
print(f"The shape of three_pm is {three_pm.shape}")




The shape of eleven_am is (4,)
The shape of three_pm is (4,)


In [8]:
# Evaluate the temperature averaged over time, at each height
avg_temp = (eleven_am + three_pm) / 2
print(f"The average temperature at each height is {avg_temp}")




The average temperature at each height is [92.5 87.5 85.5 81. ]


In [11]:
#Evaluate the temperature averaged over all heights, at each time.
avg_temp_all = np.mean(temperature, axis=0)
print(f"The average temperature at each time is {avg_temp_all}")


The average temperature at each time is [85.5  87.75]


In [ ]:
# By how much did the temperature change per hour at each height (i.e., at each vertical level?) 
# Remember: Time 1 is 11 AM, and Time 2 is 3 PM
print(f"The temperature change per hour at each height is {(eleven_am - three_pm)/4}")

# At which vertical level did the temperature change the most between 11 AM and 3 PM?





In [ ]:
# Plot the temperature profile, at each time on the same plot
# y-axis being vertical level
# x-axis being temperature















## DONE WITH THESE EXERCISES WITH TIME REMAINING?
- work on Week 4 Assignment and/or help your peers with their Qs!
- review solutions to Week 3 Assignment, Week 4 In-Module Exercises
- start looking at Week 5!

In [1]:
import numpy as np

In [2]:
numbers =  np.arange(1,6,1)
print(numbers)

[1 2 3 4 5]


In [3]:
def func_ex(vals):  

    total = 1

    for x in vals:

        total=total*x

    return total  

In [4]:
func_ex(numbers)

120

In [5]:
g = np.array([[6, 12, 4], [7, 5, 6]])
print(g)

[[ 6 12  4]
 [ 7  5  6]]


In [6]:
# minimum value in g
print(np.min(g))

4


In [8]:
# minimum value in g, along axis 0
print(np.min(g, axis=0))

[6 5 4]


In [9]:
# minimum value in g, along axis 1
print(np.min(g, axis=1))

[4 5]
